# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
# bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora
# bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, W, WhatsApp, exec, omarchy-launch-webapp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
bindd = SUPER SHIFT, E, Excalidraw, exec, omarchy-launch-webapp "https://excalidraw.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER, code:61
unbind = SUPER SHIFT, code:61
unbind = SUPER ALT, code:61
bindd = SUPER, minus, Expand window right, resizeactive, -100 0
bindd = SUPER, plus, Expand window left, resizeactive, 100 0

bindd = SUPER ALT, minus, Expand window down, resizeactive, 0 -100
bindd = SUPER ALT, plus, Expand window up, resizeactive, 0 100


# Keybinds help
unbind = SUPER, K
bindd = SUPER ALT, K, Show key bindings, exec, omarchy-menu-keybindings
unbind = SUPER SHIFT, RETURN

# Screenshot
bindd = SUPER SHIFT, S, Screenshot, exec, omarchy-capture-screenshot
bindd = SUPER SHIFT ALT, S, Screenshot with editing, exec, omarchy-capture-screenshot

unbind = SUPER, J
unbind = SUPER, L

# Control tiling
# bindd = SUPER, R, Toggle split, togglesplit, # dwindle
bindd = SUPER, R, Toggle split, layoutmsg, togglesplit # dwindle

# Move focus with vim motions
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d

#Swap active window with the one next to it
bindd = SUPER SHIFT, H, Swap window left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d


